import type { Request, Response } from 'express';
import { env } from '../../config/env';
import {
  addressRequiredServiceLocation,
  defaultServiceLocation,
  serviceLocationValues
} from '../../platform/serviceLocation.constants';
import { preferredLanguageOptions } from '../../platform/clientPlatform.types';

export const publicConfigController = (_req: Request, res: Response): void => {
  const bookingLocationLabels = {
    [serviceLocationValues[0]]: env.PUBLIC_BOOKING_LOCATION_OPTION_PHYSICAL?.trim() ?? '',
    [serviceLocationValues[1]]: env.PUBLIC_BOOKING_LOCATION_OPTION_MOBILE?.trim() ?? '',
    [serviceLocationValues[2]]: env.PUBLIC_BOOKING_LOCATION_OPTION_VIRTUAL?.trim() ?? ''
  };

  res.status(200).json({
    supportCompanyName: env.PUBLIC_SUPPORT_COMPANY_NAME?.trim() ?? '',
    supportPlatformName: env.PUBLIC_SUPPORT_PLATFORM_NAME?.trim() ?? '',
    supportWebsiteUrl: env.PUBLIC_SUPPORT_WEBSITE_URL?.trim() ?? env.PUBLIC_BASE_URL ?? '',
    supportFocusText: env.PUBLIC_SUPPORT_FOCUS_TEXT?.trim() ?? '',
    preferredLanguages: preferredLanguageOptions,
    serviceLabelSingular: env.PUBLIC_SERVICE_LABEL_SINGULAR?.trim() ?? '',
    serviceLabelPlural: env.PUBLIC_SERVICE_LABEL_PLURAL?.trim() ?? '',
    serviceMenuTitle: env.PUBLIC_SERVICE_MENU_TITLE?.trim() ?? '',
    serviceMenuDescription: env.PUBLIC_SERVICE_MENU_DESCRIPTION?.trim() ?? '',
    serviceCoverageLabel: env.PUBLIC_SERVICE_COVERAGE_LABEL?.trim() ?? '',
    serviceEmptyTitle: env.PUBLIC_SERVICE_EMPTY_TITLE?.trim() ?? '',
    serviceEmptyDescription: env.PUBLIC_SERVICE_EMPTY_DESCRIPTION?.trim() ?? '',
    serviceActionAdd: env.PUBLIC_SERVICE_ACTION_ADD?.trim() ?? '',
    serviceActionEdit: env.PUBLIC_SERVICE_ACTION_EDIT?.trim() ?? '',
    serviceActionRemove: env.PUBLIC_SERVICE_ACTION_REMOVE?.trim() ?? '',
    serviceActionSave: env.PUBLIC_SERVICE_ACTION_SAVE?.trim() ?? '',
    serviceActionUpdate: env.PUBLIC_SERVICE_ACTION_UPDATE?.trim() ?? '',
    serviceActionOpenBooking: env.PUBLIC_SERVICE_ACTION_OPEN_BOOKING?.trim() ?? '',
    serviceActionStayInCatalog: env.PUBLIC_SERVICE_ACTION_STAY_IN_CATALOG?.trim() ?? '',
    serviceFieldNameLabel: env.PUBLIC_SERVICE_FIELD_NAME_LABEL?.trim() ?? '',
    serviceFieldCategoryLabel: env.PUBLIC_SERVICE_FIELD_CATEGORY_LABEL?.trim() ?? '',
    serviceFieldDurationLabel: env.PUBLIC_SERVICE_FIELD_DURATION_LABEL?.trim() ?? '',
    serviceFieldPriceLabel: env.PUBLIC_SERVICE_FIELD_PRICE_LABEL?.trim() ?? '',
    serviceFieldDescriptionLabel: env.PUBLIC_SERVICE_FIELD_DESCRIPTION_LABEL?.trim() ?? '',
    serviceFormAddDescription: env.PUBLIC_SERVICE_FORM_ADD_DESCRIPTION?.trim() ?? '',
    serviceFormEditDescription: env.PUBLIC_SERVICE_FORM_EDIT_DESCRIPTION?.trim() ?? '',
    serviceValidationRequired: env.PUBLIC_SERVICE_VALIDATION_REQUIRED?.trim() ?? '',
    serviceValidationDuration: env.PUBLIC_SERVICE_VALIDATION_DURATION?.trim() ?? '',
    serviceErrorAdd: env.PUBLIC_SERVICE_ERROR_ADD?.trim() ?? '',
    serviceErrorUpdate: env.PUBLIC_SERVICE_ERROR_UPDATE?.trim() ?? '',
    serviceErrorRemove: env.PUBLIC_SERVICE_ERROR_REMOVE?.trim() ?? '',
    packageLabelSingular: env.PUBLIC_PACKAGE_LABEL_SINGULAR?.trim() ?? '',
    packageLabelPlural: env.PUBLIC_PACKAGE_LABEL_PLURAL?.trim() ?? '',
    packageMenuTitle: env.PUBLIC_PACKAGE_MENU_TITLE?.trim() ?? '',
    packageMenuDescription: env.PUBLIC_PACKAGE_MENU_DESCRIPTION?.trim() ?? '',
    packageEmptyTitle: env.PUBLIC_PACKAGE_EMPTY_TITLE?.trim() ?? '',
    packageEmptyDescription: env.PUBLIC_PACKAGE_EMPTY_DESCRIPTION?.trim() ?? '',
    packageActionAdd: env.PUBLIC_PACKAGE_ACTION_ADD?.trim() ?? '',
    packageActionEdit: env.PUBLIC_PACKAGE_ACTION_EDIT?.trim() ?? '',
    packageActionRemove: env.PUBLIC_PACKAGE_ACTION_REMOVE?.trim() ?? '',
    packageActionSave: env.PUBLIC_PACKAGE_ACTION_SAVE?.trim() ?? '',
    packageActionUpdate: env.PUBLIC_PACKAGE_ACTION_UPDATE?.trim() ?? '',
    packageActionSell: env.PUBLIC_PACKAGE_ACTION_SELL?.trim() ?? '',
    packageActionOpenReports: env.PUBLIC_PACKAGE_ACTION_OPEN_REPORTS?.trim() ?? '',
    packageActionOpenCatalog: env.PUBLIC_PACKAGE_ACTION_OPEN_CATALOG?.trim() ?? '',
    packageFieldNameLabel: env.PUBLIC_PACKAGE_FIELD_NAME_LABEL?.trim() ?? '',
    packageFieldTotalUsesLabel: env.PUBLIC_PACKAGE_FIELD_TOTAL_USES_LABEL?.trim() ?? '',
    packageFieldPriceLabel: env.PUBLIC_PACKAGE_FIELD_PRICE_LABEL?.trim() ?? '',
    packageFieldIncludedServicesLabel: env.PUBLIC_PACKAGE_FIELD_INCLUDED_SERVICES_LABEL?.trim() ?? '',
    packageFormAddDescription: env.PUBLIC_PACKAGE_FORM_ADD_DESCRIPTION?.trim() ?? '',
    packageFormEditDescription: env.PUBLIC_PACKAGE_FORM_EDIT_DESCRIPTION?.trim() ?? '',
    packageValidationRequired: env.PUBLIC_PACKAGE_VALIDATION_REQUIRED?.trim() ?? '',
    packageErrorAdd: env.PUBLIC_PACKAGE_ERROR_ADD?.trim() ?? '',
    packageErrorUpdate: env.PUBLIC_PACKAGE_ERROR_UPDATE?.trim() ?? '',
    packageErrorRemove: env.PUBLIC_PACKAGE_ERROR_REMOVE?.trim() ?? '',
    packageSoldLabel: env.PUBLIC_PACKAGE_SOLD_LABEL?.trim() ?? '',
    packageActiveBalancesLabel: env.PUBLIC_PACKAGE_ACTIVE_BALANCES_LABEL?.trim() ?? '',
    packagePublishedLabel: env.PUBLIC_PACKAGE_PUBLISHED_LABEL?.trim() ?? '',
    productLabelSingular: env.PUBLIC_PRODUCT_LABEL_SINGULAR?.trim() ?? '',
    productLabelPlural: env.PUBLIC_PRODUCT_LABEL_PLURAL?.trim() ?? '',
    productMenuTitle: env.PUBLIC_PRODUCT_MENU_TITLE?.trim() ?? '',
    productMenuDescription: env.PUBLIC_PRODUCT_MENU_DESCRIPTION?.trim() ?? '',
    productEmptyTitle: env.PUBLIC_PRODUCT_EMPTY_TITLE?.trim() ?? '',
    productEmptyDescription: env.PUBLIC_PRODUCT_EMPTY_DESCRIPTION?.trim() ?? '',
    productActionAdd: env.PUBLIC_PRODUCT_ACTION_ADD?.trim() ?? '',
    productActionEdit: env.PUBLIC_PRODUCT_ACTION_EDIT?.trim() ?? '',
    productActionRemove: env.PUBLIC_PRODUCT_ACTION_REMOVE?.trim() ?? '',
    productActionSave: env.PUBLIC_PRODUCT_ACTION_SAVE?.trim() ?? '',
    productActionUpdate: env.PUBLIC_PRODUCT_ACTION_UPDATE?.trim() ?? '',
    productActionSell: env.PUBLIC_PRODUCT_ACTION_SELL?.trim() ?? '',
    productActionViewRecords: env.PUBLIC_PRODUCT_ACTION_VIEW_RECORDS?.trim() ?? '',
    productActionOpenReports: env.PUBLIC_PRODUCT_ACTION_OPEN_REPORTS?.trim() ?? '',
    productFieldNameLabel: env.PUBLIC_PRODUCT_FIELD_NAME_LABEL?.trim() ?? '',
    productFieldCategoryLabel: env.PUBLIC_PRODUCT_FIELD_CATEGORY_LABEL?.trim() ?? '',
    productFieldSkuLabel: env.PUBLIC_PRODUCT_FIELD_SKU_LABEL?.trim() ?? '',
    productFieldPriceLabel: env.PUBLIC_PRODUCT_FIELD_PRICE_LABEL?.trim() ?? '',
    productFieldStockLabel: env.PUBLIC_PRODUCT_FIELD_STOCK_LABEL?.trim() ?? '',
    productFieldDescriptionLabel: env.PUBLIC_PRODUCT_FIELD_DESCRIPTION_LABEL?.trim() ?? '',
    productFieldQuantityLabel: env.PUBLIC_PRODUCT_FIELD_QUANTITY_LABEL?.trim() ?? '',
    productFieldCustomerNameLabel: env.PUBLIC_PRODUCT_FIELD_CUSTOMER_NAME_LABEL?.trim() ?? '',
    productFieldCustomerPhoneLabel: env.PUBLIC_PRODUCT_FIELD_CUSTOMER_PHONE_LABEL?.trim() ?? '',
    productFieldCustomerEmailLabel: env.PUBLIC_PRODUCT_FIELD_CUSTOMER_EMAIL_LABEL?.trim() ?? '',
    productFormAddDescription: env.PUBLIC_PRODUCT_FORM_ADD_DESCRIPTION?.trim() ?? '',
    productFormEditDescription: env.PUBLIC_PRODUCT_FORM_EDIT_DESCRIPTION?.trim() ?? '',
    productSalesDescription: env.PUBLIC_PRODUCT_SALES_DESCRIPTION?.trim() ?? '',
    productValidationRequired: env.PUBLIC_PRODUCT_VALIDATION_REQUIRED?.trim() ?? '',
    productValidationStock: env.PUBLIC_PRODUCT_VALIDATION_STOCK?.trim() ?? '',
    productErrorAdd: env.PUBLIC_PRODUCT_ERROR_ADD?.trim() ?? '',
    productErrorUpdate: env.PUBLIC_PRODUCT_ERROR_UPDATE?.trim() ?? '',
    productErrorRemove: env.PUBLIC_PRODUCT_ERROR_REMOVE?.trim() ?? '',
    productErrorSell: env.PUBLIC_PRODUCT_ERROR_SELL?.trim() ?? '',
    productMetricActiveLabel: env.PUBLIC_PRODUCT_METRIC_ACTIVE_LABEL?.trim() ?? '',
    productMetricStockLabel: env.PUBLIC_PRODUCT_METRIC_STOCK_LABEL?.trim() ?? '',
    productMetricSoldLabel: env.PUBLIC_PRODUCT_METRIC_SOLD_LABEL?.trim() ?? '',
    productMetricLowStockLabel: env.PUBLIC_PRODUCT_METRIC_LOW_STOCK_LABEL?.trim() ?? '',
    profileTitleSuffix: env.PUBLIC_PROFILE_TITLE_SUFFIX?.trim() ?? '',
    profileDescription: env.PUBLIC_PROFILE_DESCRIPTION?.trim() ?? '',
    profileFieldBusinessNameLabel: env.PUBLIC_PROFILE_FIELD_BUSINESS_NAME_LABEL?.trim() ?? '',
    profileFieldBusinessNamePlaceholder: env.PUBLIC_PROFILE_FIELD_BUSINESS_NAME_PLACEHOLDER?.trim() ?? '',
    profileFieldWebsiteLabel: env.PUBLIC_PROFILE_FIELD_WEBSITE_LABEL?.trim() ?? '',
    profileFieldWebsitePlaceholder: env.PUBLIC_PROFILE_FIELD_WEBSITE_PLACEHOLDER?.trim() ?? '',
    profileFieldAddressLabel: env.PUBLIC_PROFILE_FIELD_ADDRESS_LABEL?.trim() ?? '',
    profileFieldAddressPlaceholder: env.PUBLIC_PROFILE_FIELD_ADDRESS_PLACEHOLDER?.trim() ?? '',
    profileFieldImageLabel: env.PUBLIC_PROFILE_FIELD_IMAGE_LABEL?.trim() ?? '',
    profileFieldImagePlaceholder: env.PUBLIC_PROFILE_FIELD_IMAGE_PLACEHOLDER?.trim() ?? '',
    profileActionUploadImage: env.PUBLIC_PROFILE_ACTION_UPLOAD_IMAGE?.trim() ?? '',
    profileActionRemoveImage: env.PUBLIC_PROFILE_ACTION_REMOVE_IMAGE?.trim() ?? '',
    profileActionSave: env.PUBLIC_PROFILE_ACTION_SAVE?.trim() ?? '',
    profileValidationRequired: env.PUBLIC_PROFILE_VALIDATION_REQUIRED?.trim() ?? '',
    profileErrorUpdate: env.PUBLIC_PROFILE_ERROR_UPDATE?.trim() ?? '',
    teamMemberLabelSingular: env.PUBLIC_TEAM_MEMBER_LABEL_SINGULAR?.trim() ?? '',
    teamMemberLabelPlural: env.PUBLIC_TEAM_MEMBER_LABEL_PLURAL?.trim() ?? '',
    teamMemberRoleOptions: env.PUBLIC_TEAM_MEMBER_ROLE_OPTIONS,
    teamMemberFieldOpeningTimeLabel: env.PUBLIC_TEAM_MEMBER_FIELD_OPENING_TIME_LABEL?.trim() ?? '',
    teamMemberFieldClosingTimeLabel: env.PUBLIC_TEAM_MEMBER_FIELD_CLOSING_TIME_LABEL?.trim() ?? '',
    teamMemberFieldOffDaysLabel: env.PUBLIC_TEAM_MEMBER_FIELD_OFF_DAYS_LABEL?.trim() ?? '',
    teamMemberFieldOffDaysEmpty: env.PUBLIC_TEAM_MEMBER_FIELD_OFF_DAYS_EMPTY?.trim() ?? '',
    bookingLocationLabel: env.PUBLIC_BOOKING_LOCATION_LABEL?.trim() ?? '',
    bookingLocationLabels,
    bookingDefaultLocationValue: defaultServiceLocation,
    bookingAddressLocationValue: addressRequiredServiceLocation,
    bookingLocationOptionPhysical: env.PUBLIC_BOOKING_LOCATION_OPTION_PHYSICAL?.trim() ?? '',
    bookingLocationOptionMobile: env.PUBLIC_BOOKING_LOCATION_OPTION_MOBILE?.trim() ?? '',
    bookingLocationOptionVirtual: env.PUBLIC_BOOKING_LOCATION_OPTION_VIRTUAL?.trim() ?? '',
    bookingAddressLabel: env.PUBLIC_BOOKING_ADDRESS_LABEL?.trim() ?? '',
    bookingAddressPlaceholder: env.PUBLIC_BOOKING_ADDRESS_PLACEHOLDER?.trim() ?? '',
    bookingAddressHelp: env.PUBLIC_BOOKING_ADDRESS_HELP?.trim() ?? '',
    bookingAddressRequired: env.PUBLIC_BOOKING_ADDRESS_REQUIRED?.trim() ?? '',
    bookingPhoneLabel: env.PUBLIC_BOOKING_PHONE_LABEL?.trim() ?? '',
    bookingPhoneHelp: env.PUBLIC_BOOKING_PHONE_HELP?.trim() ?? '',
    bookingPhoneCountryCodeLabel: env.PUBLIC_BOOKING_PHONE_COUNTRY_CODE_LABEL?.trim() ?? '',
    bookingPhoneCountryCode: env.PUBLIC_BOOKING_PHONE_COUNTRY_CODE?.trim() ?? '',
    bookingPhoneNumberPlaceholder: env.PUBLIC_BOOKING_PHONE_NUMBER_PLACEHOLDER?.trim() ?? '',
    homeSearchResultsLimit: env.PUBLIC_HOME_SEARCH_RESULTS_LIMIT,
    locationSearchCountryCode: env.PUBLIC_LOCATION_SEARCH_COUNTRY_CODE?.trim().toLowerCase() ?? '',
    locationSearchCountryLabel: env.PUBLIC_LOCATION_SEARCH_COUNTRY_LABEL?.trim() ?? ''
  });
};
