import { getSupabaseClient } from '../shared/supabase/client';
import type {
  CampaignChannel,
  CampaignDispatchStatus,
  CampaignRecipientOrigin,
  CampaignRecipientRecord,
  CampaignRecipientSource,
  CampaignRecord,
  CampaignStatus,
  CampaignTemplateRecord,
  CampaignTemplateType
} from './marketing.types';

type Row = Record<string, unknown>;

const asText = (value: unknown): string => (typeof value === 'string' ? value.trim() : '');

const asNullableText = (value: unknown): string | undefined => {
  const text = asText(value);
  return text ? text : undefined;
};

const asNumber = (value: unknown, fallback = 0): number =>
  typeof value === 'number' && Number.isFinite(value) ? value : fallback;

const asNullableNumber = (value: unknown): number | undefined =>
  typeof value === 'number' && Number.isFinite(value) ? value : undefined;

const asTimestamp = (value: unknown): string => {
  const text = asNullableText(value);
  return text ?? new Date().toISOString();
};

const campaignToRow = (campaign: CampaignRecord): Row => ({
  id: campaign.id,
  business_id: campaign.businessId,
  name: campaign.name,
  template_type: campaign.templateType,
  discount_percent: campaign.discountPercent ?? null,
  discount_amount_cents: campaign.discountAmountCents ?? null,
  currency_code: campaign.currencyCode,
  target_service_id: campaign.targetServiceId ?? null,
  target_service_name: campaign.targetServiceName,
  free_service_id: campaign.freeServiceId ?? null,
  free_service_name: campaign.freeServiceName,
  happy_hour_start_time: campaign.happyHourStartTime ?? null,
  happy_hour_end_time: campaign.happyHourEndTime ?? null,
  offer_name: campaign.offerName ?? '',
  original_price_cents: campaign.originalPriceCents ?? null,
  discounted_price_cents: campaign.discountedPriceCents ?? null,
  fill_slot_date: campaign.fillSlotDate ?? null,
  fill_slot_time: campaign.fillSlotTime ?? null,
  is_auto_generated: campaign.isAutoGenerated,
  sms_body: campaign.smsBody,
  email_subject: campaign.emailSubject,
  email_body_text: campaign.emailBodyText,
  channel: campaign.channel,
  recipient_source: campaign.recipientSource,
  status: campaign.status,
  recipients_total: campaign.recipientsTotal,
  recipients_sent: campaign.recipientsSent,
  recipients_failed: campaign.recipientsFailed,
  recipients_skipped: campaign.recipientsSkipped,
  booking_link: campaign.bookingLink,
  is_promoted_on_marketplace: campaign.isPromotedOnMarketplace,
  marketplace_offer_title: campaign.marketplaceOfferTitle ?? null,
  marketplace_service_ids: campaign.marketplaceServiceIds,
  marketplace_start_date: campaign.marketplaceStartDate ?? null,
  marketplace_end_date: campaign.marketplaceEndDate ?? null,
  marketplace_branch_id: campaign.marketplaceBranchId ?? null,
  marketplace_redemption_cap: campaign.marketplaceRedemptionCap ?? null,
  marketplace_new_customer_only: campaign.marketplaceNewCustomerOnly,
  marketplace_cta_label: campaign.marketplaceCtaLabel,
  created_at: campaign.createdAt,
  updated_at: campaign.updatedAt,
  sent_at: campaign.sentAt ?? null
});

const asBoolean = (value: unknown, fallback = false): boolean =>
  typeof value === 'boolean' ? value : fallback;

const rowToCampaign = (row: Row): CampaignRecord => ({
  id: asText(row.id),
  businessId: asText(row.business_id),
  name: asText(row.name),
  templateType: asText(row.template_type) as CampaignTemplateType,
  discountPercent: asNullableNumber(row.discount_percent),
  discountAmountCents: asNullableNumber(row.discount_amount_cents),
  currencyCode: asText(row.currency_code),
  targetServiceId: asNullableText(row.target_service_id),
  targetServiceName: asText(row.target_service_name),
  freeServiceId: asNullableText(row.free_service_id),
  freeServiceName: asText(row.free_service_name),
  happyHourStartTime: asNullableText(row.happy_hour_start_time),
  happyHourEndTime: asNullableText(row.happy_hour_end_time),
  offerName: asText(row.offer_name),
  originalPriceCents: asNullableNumber(row.original_price_cents),
  discountedPriceCents: asNullableNumber(row.discounted_price_cents),
  fillSlotDate: asNullableText(row.fill_slot_date),
  fillSlotTime: asNullableText(row.fill_slot_time),
  isAutoGenerated: asBoolean(row.is_auto_generated),
  smsBody: asText(row.sms_body),
  emailSubject: asText(row.email_subject),
  emailBodyText: asText(row.email_body_text),
  channel: asText(row.channel) as CampaignChannel,
  recipientSource: asText(row.recipient_source) as CampaignRecipientSource,
  status: asText(row.status) as CampaignStatus,
  recipientsTotal: asNumber(row.recipients_total),
  recipientsSent: asNumber(row.recipients_sent),
  recipientsFailed: asNumber(row.recipients_failed),
  recipientsSkipped: asNumber(row.recipients_skipped),
  linkOpensCount: asNumber(row.link_opens_count),
  bookingLink: asText(row.booking_link),
  isPromotedOnMarketplace: asBoolean(row.is_promoted_on_marketplace),
  marketplaceOfferTitle: asNullableText(row.marketplace_offer_title),
  marketplaceServiceIds: Array.isArray(row.marketplace_service_ids)
    ? (row.marketplace_service_ids as unknown[]).filter((entry): entry is string => typeof entry === 'string')
    : [],
  marketplaceStartDate: asNullableText(row.marketplace_start_date),
  marketplaceEndDate: asNullableText(row.marketplace_end_date),
  marketplaceBranchId: asNullableText(row.marketplace_branch_id),
  marketplaceRedemptionCap: asNullableNumber(row.marketplace_redemption_cap),
  marketplaceNewCustomerOnly: asBoolean(row.marketplace_new_customer_only),
  marketplaceCtaLabel: asText(row.marketplace_cta_label) || 'Book Offer',
  createdAt: asTimestamp(row.created_at),
  updatedAt: asTimestamp(row.updated_at),
  sentAt: asNullableText(row.sent_at)
});

const recipientToRow = (recipient: CampaignRecipientRecord): Row => ({
  id: recipient.id,
  campaign_id: recipient.campaignId,
  business_id: recipient.businessId,
  origin: recipient.origin,
  customer_profile_id: recipient.customerProfileId ?? null,
  customer_name: recipient.customerName,
  customer_phone: recipient.customerPhone,
  customer_email: recipient.customerEmail,
  dedupe_key: recipient.dedupeKey,
  sms_status: recipient.smsStatus,
  sms_reason: recipient.smsReason,
  sms_message_id: recipient.smsMessageId,
  email_status: recipient.emailStatus,
  email_reason: recipient.emailReason,
  converted_appointment_id: recipient.convertedAppointmentId ?? null,
  converted_at: recipient.convertedAt ?? null,
  opened_at: recipient.openedAt ?? null,
  created_at: recipient.createdAt,
  updated_at: recipient.updatedAt
});

const rowToRecipient = (row: Row): CampaignRecipientRecord => ({
  id: asText(row.id),
  campaignId: asText(row.campaign_id),
  businessId: asText(row.business_id),
  origin: asText(row.origin) as CampaignRecipientOrigin,
  customerProfileId: asNullableText(row.customer_profile_id),
  customerName: asText(row.customer_name),
  customerPhone: asText(row.customer_phone),
  customerEmail: asText(row.customer_email),
  dedupeKey: asText(row.dedupe_key),
  smsStatus: asText(row.sms_status) as CampaignDispatchStatus,
  smsReason: asText(row.sms_reason),
  smsMessageId: asText(row.sms_message_id),
  emailStatus: asText(row.email_status) as CampaignDispatchStatus,
  emailReason: asText(row.email_reason),
  convertedAppointmentId: asNullableText(row.converted_appointment_id),
  convertedAt: asNullableText(row.converted_at),
  openedAt: asNullableText(row.opened_at),
  createdAt: asTimestamp(row.created_at),
  updatedAt: asTimestamp(row.updated_at)
});

const templateToRow = (template: CampaignTemplateRecord): Row => ({
  id: template.id,
  business_id: template.businessId,
  template_type: template.templateType,
  sms_body: template.smsBody,
  email_subject: template.emailSubject,
  email_body_text: template.emailBodyText,
  default_discount_percent: template.defaultDiscountPercent ?? null,
  updated_at: template.updatedAt
});

const rowToTemplate = (row: Row): CampaignTemplateRecord => ({
  id: asText(row.id),
  businessId: asText(row.business_id),
  templateType: asText(row.template_type) as CampaignTemplateType,
  smsBody: asText(row.sms_body),
  emailSubject: asText(row.email_subject),
  emailBodyText: asText(row.email_body_text),
  defaultDiscountPercent: asNullableNumber(row.default_discount_percent),
  updatedAt: asTimestamp(row.updated_at)
});

export const marketingRepository = {
  async createCampaign(campaign: CampaignRecord): Promise<CampaignRecord> {
    const client = getSupabaseClient();
    const { error } = await client.from('marketing_campaigns').insert(campaignToRow(campaign));

    if (error) {
      throw new Error(`Failed to create campaign: ${error.message}`);
    }

    return campaign;
  },

  async updateCampaign(campaign: CampaignRecord): Promise<CampaignRecord> {
    const client = getSupabaseClient();
    const { error } = await client
      .from('marketing_campaigns')
      .update(campaignToRow(campaign))
      .eq('id', campaign.id);

    if (error) {
      throw new Error(`Failed to update campaign ${campaign.id}: ${error.message}`);
    }

    return campaign;
  },

  async incrementLinkOpens(campaignId: string): Promise<void> {
    const client = getSupabaseClient();
    const { data, error: readError } = await client
      .from('marketing_campaigns')
      .select('link_opens_count')
      .eq('id', campaignId)
      .maybeSingle();

    if (readError) {
      throw new Error(`Failed to read link opens for campaign ${campaignId}: ${readError.message}`);
    }

    if (!data) {
      return;
    }

    const nextCount = asNumber(data.link_opens_count) + 1;
    const { error: writeError } = await client
      .from('marketing_campaigns')
      .update({ link_opens_count: nextCount, updated_at: new Date().toISOString() })
      .eq('id', campaignId);

    if (writeError) {
      throw new Error(`Failed to increment link opens for campaign ${campaignId}: ${writeError.message}`);
    }
  },

  async getCampaignById(businessId: string, campaignId: string): Promise<CampaignRecord | undefined> {
    const client = getSupabaseClient();
    const { data, error } = await client
      .from('marketing_campaigns')
      .select('*')
      .eq('business_id', businessId)
      .eq('id', campaignId)
      .maybeSingle();

    if (error) {
      throw new Error(`Failed to load campaign ${campaignId}: ${error.message}`);
    }

    return data ? rowToCampaign(data as Row) : undefined;
  },

  async countActiveMarketplaceOffers(businessId: string): Promise<number> {
    const client = getSupabaseClient();
    const todayDate = new Date().toISOString().slice(0, 10);
    const { count, error } = await client
      .from('marketing_campaigns')
      .select('*', { count: 'exact', head: true })
      .eq('business_id', businessId)
      .eq('is_promoted_on_marketplace', true)
      .or(`marketplace_end_date.is.null,marketplace_end_date.gte.${todayDate}`);

    if (error) {
      throw new Error(`Failed to count active marketplace offers for ${businessId}: ${error.message}`);
    }

    return count ?? 0;
  },

  async listCampaignsByBusinessId(businessId: string): Promise<CampaignRecord[]> {
    const client = getSupabaseClient();
    const { data, error } = await client
      .from('marketing_campaigns')
      .select('*')
      .eq('business_id', businessId)
      .order('created_at', { ascending: false });

    if (error) {
      throw new Error(`Failed to list campaigns for ${businessId}: ${error.message}`);
    }

    return (data ?? []).map((row) => rowToCampaign(row as Row));
  },

  async insertRecipients(recipients: CampaignRecipientRecord[]): Promise<void> {
    if (recipients.length === 0) {
      return;
    }

    const client = getSupabaseClient();
    const { error } = await client
      .from('marketing_campaign_recipients')
      .upsert(recipients.map(recipientToRow), { onConflict: 'campaign_id,dedupe_key' });

    if (error) {
      throw new Error(`Failed to insert campaign recipients: ${error.message}`);
    }
  },

  async updateRecipient(recipient: CampaignRecipientRecord): Promise<void> {
    const client = getSupabaseClient();
    const { error } = await client
      .from('marketing_campaign_recipients')
      .update(recipientToRow(recipient))
      .eq('id', recipient.id);

    if (error) {
      throw new Error(`Failed to update campaign recipient ${recipient.id}: ${error.message}`);
    }
  },

  // Records the recipient's first link open. Sets opened_at only when it is
  // still null, and returns true if this was the first (unique) open.
  async markRecipientOpened(recipientId: string): Promise<boolean> {
    const client = getSupabaseClient();
    const now = new Date().toISOString();
    const { data, error } = await client
      .from('marketing_campaign_recipients')
      .update({ opened_at: now, updated_at: now })
      .eq('id', recipientId)
      .is('opened_at', null)
      .select('id');

    if (error) {
      throw new Error(`Failed to mark recipient ${recipientId} opened: ${error.message}`);
    }

    return Array.isArray(data) && data.length > 0;
  },

  // Counts unique recipients who opened, per campaign, for a business. Used to
  // keep the opens shown everywhere consistent with the per-recipient records.
  async countOpensByBusinessId(businessId: string): Promise<Map<string, number>> {
    const client = getSupabaseClient();
    const { data, error } = await client
      .from('marketing_campaign_recipients')
      .select('campaign_id')
      .eq('business_id', businessId)
      .not('opened_at', 'is', null);

    if (error) {
      throw new Error(`Failed to count opens for business ${businessId}: ${error.message}`);
    }

    const counts = new Map<string, number>();
    for (const row of data ?? []) {
      const campaignId = asText((row as Row).campaign_id);
      counts.set(campaignId, (counts.get(campaignId) ?? 0) + 1);
    }

    return counts;
  },

  async listRecipientsByCampaignId(campaignId: string): Promise<CampaignRecipientRecord[]> {
    const client = getSupabaseClient();
    const { data, error } = await client
      .from('marketing_campaign_recipients')
      .select('*')
      .eq('campaign_id', campaignId)
      .order('created_at', { ascending: true });

    if (error) {
      throw new Error(`Failed to list recipients for campaign ${campaignId}: ${error.message}`);
    }

    return (data ?? []).map((row) => rowToRecipient(row as Row));
  },

  async findRecipientsByBusinessAndContact(
    businessId: string,
    campaignId: string,
    phone: string,
    email: string
  ): Promise<CampaignRecipientRecord[]> {
    const client = getSupabaseClient();
    let query = client
      .from('marketing_campaign_recipients')
      .select('*')
      .eq('business_id', businessId)
      .eq('campaign_id', campaignId);

    if (phone && email) {
      query = query.or(`customer_phone.eq.${phone},customer_email.eq.${email}`);
    } else if (phone) {
      query = query.eq('customer_phone', phone);
    } else if (email) {
      query = query.eq('customer_email', email);
    } else {
      return [];
    }

    const { data, error } = await query;

    if (error) {
      throw new Error(`Failed to find recipients for conversion match: ${error.message}`);
    }

    return (data ?? []).map((row) => rowToRecipient(row as Row));
  },

  async getTemplate(
    businessId: string,
    templateType: CampaignTemplateType
  ): Promise<CampaignTemplateRecord | undefined> {
    const client = getSupabaseClient();
    const { data, error } = await client
      .from('marketing_campaign_templates')
      .select('*')
      .eq('business_id', businessId)
      .eq('template_type', templateType)
      .maybeSingle();

    if (error) {
      throw new Error(`Failed to load template ${templateType} for ${businessId}: ${error.message}`);
    }

    return data ? rowToTemplate(data as Row) : undefined;
  },

  async upsertTemplate(template: CampaignTemplateRecord): Promise<CampaignTemplateRecord> {
    const client = getSupabaseClient();
    const { error } = await client
      .from('marketing_campaign_templates')
      .upsert(templateToRow(template), { onConflict: 'business_id,template_type' });

    if (error) {
      throw new Error(`Failed to save template ${template.templateType}: ${error.message}`);
    }

    return template;
  }
};
