export type CampaignTemplateType =
  | 'percent_off'
  | 'flat_amount_off'
  | 'free_service'
  | 'happy_hour'
  | 'last_minute_fill';
export type CampaignChannel = 'sms' | 'email' | 'both';
export type CampaignRecipientSource = 'existing_clients' | 'csv_upload' | 'both' | 'random_batch';
export type CampaignStatus = 'draft' | 'sending' | 'sent' | 'failed' | 'partially_sent';
export type CampaignDispatchStatus = 'pending' | 'sent' | 'failed' | 'skipped' | 'not_applicable';
export type CampaignRecipientOrigin = 'existing_client' | 'csv_upload';

export interface CampaignRecord {
  id: string;
  businessId: string;
  name: string;
  templateType: CampaignTemplateType;
  discountPercent?: number;
  discountAmountCents?: number;
  currencyCode: string;
  targetServiceId?: string;
  targetServiceName: string;
  freeServiceId?: string;
  freeServiceName: string;
  happyHourStartTime?: string;
  happyHourEndTime?: string;
  offerName?: string;
  originalPriceCents?: number;
  discountedPriceCents?: number;
  fillSlotDate?: string;
  fillSlotTime?: string;
  isAutoGenerated: boolean;
  smsBody: string;
  emailSubject: string;
  emailBodyText: string;
  channel: CampaignChannel;
  recipientSource: CampaignRecipientSource;
  status: CampaignStatus;
  recipientsTotal: number;
  recipientsSent: number;
  recipientsFailed: number;
  recipientsSkipped: number;
  linkOpensCount: number;
  bookingLink: string;
  createdAt: string;
  updatedAt: string;
  sentAt?: string;
}

export interface CampaignRecipientRecord {
  id: string;
  campaignId: string;
  businessId: string;
  origin: CampaignRecipientOrigin;
  customerProfileId?: string;
  customerName: string;
  customerPhone: string;
  customerEmail: string;
  dedupeKey: string;
  smsStatus: CampaignDispatchStatus;
  smsReason: string;
  smsMessageId: string;
  emailStatus: CampaignDispatchStatus;
  emailReason: string;
  convertedAppointmentId?: string;
  convertedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CampaignTemplateRecord {
  id: string;
  businessId: string;
  templateType: CampaignTemplateType;
  smsBody: string;
  emailSubject: string;
  emailBodyText: string;
  defaultDiscountPercent?: number;
  updatedAt: string;
}

export interface CampaignWithStats extends CampaignRecord {
  conversionsCount: number;
}

export interface CsvContactRow {
  name: string;
  phone: string;
  email: string;
}

export interface CreateCampaignInput {
  name: string;
  templateType: CampaignTemplateType;
  discountPercent?: number;
  discountAmountCents?: number;
  currencyCode?: string;
  targetServiceId?: string;
  freeServiceId?: string;
  happyHourStartTime?: string;
  happyHourEndTime?: string;
  offerName?: string;
  originalPriceCents?: number;
  discountedPriceCents?: number;
  smsBody: string;
  emailSubject: string;
  emailBodyText: string;
  channel: CampaignChannel;
  recipientSource: CampaignRecipientSource;
}

export interface RecipientPreview {
  recipients: {
    name: string;
    phone: string;
    email: string;
    origin: CampaignRecipientOrigin;
  }[];
  total: number;
  smsEligibleCount: number;
  emailEligibleCount: number;
}
