import { z } from 'zod';
import dotenv from 'dotenv';
import {
  defaultBookingAddressHelp,
  defaultBookingAddressLabel,
  defaultBookingAddressPlaceholder,
  defaultBookingAddressRequiredMessage,
  defaultBookingLocationLabel,
  defaultBookingLocationLabels
} from '../platform/serviceLocation.constants';

dotenv.config();

const parseBooleanEnv = (value: string | undefined, fallback: boolean): boolean => {
  if (typeof value !== 'string') {
    return fallback;
  }

  const normalizedValue = value.trim().toLowerCase();

  if (['1', 'true', 'yes', 'on'].includes(normalizedValue)) {
    return true;
  }

  if (['0', 'false', 'no', 'off'].includes(normalizedValue)) {
    return false;
  }

  return fallback;
};

const normalizeBaseUrl = (value: string | undefined): string | undefined => {
  if (typeof value !== 'string' || value.trim().length === 0) {
    return undefined;
  }

  return value.trim().replace(/\/+$/, '');
};

const parseCorsOrigins = (value: string | undefined): string[] => {
  if (typeof value !== 'string' || value.trim().length === 0) {
    return [];
  }

  return value
    .split(',')
    .map((origin) => origin.trim())
    .filter((origin) => origin.length > 0);
};

const parseStringList = (value: string | undefined): string[] => {
  if (typeof value !== 'string' || value.trim().length === 0) {
    return [];
  }

  return value
    .split(',')
    .map((entry) => entry.trim())
    .filter((entry) => entry.length > 0);
};

const envSchema = z.object({
  PORT: z.coerce.number().int().positive().default(8000),
  APP_ENV: z.enum(['dev', 'prod', 'test']).default('dev'),
  LOG_LEVEL: z.enum(['debug', 'info', 'warn', 'error']).default('info'),
  CLIENT_PLATFORM_STORAGE: z.enum(['file', 'memory', 'supabase']).default('file'),
  APP_TIMEZONE: z.string().trim().min(1).default('UTC'),
  DEFAULT_BUSINESS_CURRENCY_CODE: z.string().trim().length(3).default('USD'),
  DEFAULT_BUSINESS_CURRENCY_LOCALE: z.string().trim().min(2).max(32).default('en-US'),
  WAITLIST_OFFER_WINDOW_MINUTES: z.coerce.number().int().positive().default(10),
  TRUST_PROXY: z.boolean().default(false),
  PUBLIC_BASE_URL: z.string().url().optional(),
  CORS_ALLOWED_ORIGINS: z.array(z.string().url()).default([]),
  SUPABASE_URL: z.string().url().optional(),
  SUPABASE_PUBLISHABLE_KEY: z.string().trim().min(1).optional(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().trim().min(1).optional(),
  ENABLE_PUBLIC_CUSTOMER_LOOKUPS: z.boolean().default(false),
  PLATFORM_ADMIN_COOKIE_NAME: z.string().trim().min(1).default('platform_admin_session'),
  ADMIN_SESSION_TTL_DAYS: z.coerce.number().int().positive().default(30),
  PUBLIC_SUPPORT_COMPANY_NAME: z.string().optional(),
  PUBLIC_SUPPORT_PLATFORM_NAME: z.string().optional(),
  PUBLIC_SUPPORT_WEBSITE_URL: z.string().url().optional(),
  PUBLIC_SUPPORT_FOCUS_TEXT: z.string().optional(),
  PUBLIC_SERVICE_LABEL_SINGULAR: z.string().optional(),
  PUBLIC_SERVICE_LABEL_PLURAL: z.string().optional(),
  PUBLIC_SERVICE_MENU_TITLE: z.string().optional(),
  PUBLIC_SERVICE_MENU_DESCRIPTION: z.string().optional(),
  PUBLIC_SERVICE_COVERAGE_LABEL: z.string().optional(),
  PUBLIC_SERVICE_EMPTY_TITLE: z.string().optional(),
  PUBLIC_SERVICE_EMPTY_DESCRIPTION: z.string().optional(),
  PUBLIC_SERVICE_ACTION_ADD: z.string().optional(),
  PUBLIC_SERVICE_ACTION_EDIT: z.string().optional(),
  PUBLIC_SERVICE_ACTION_REMOVE: z.string().optional(),
  PUBLIC_SERVICE_ACTION_SAVE: z.string().optional(),
  PUBLIC_SERVICE_ACTION_UPDATE: z.string().optional(),
  PUBLIC_SERVICE_ACTION_OPEN_BOOKING: z.string().optional(),
  PUBLIC_SERVICE_ACTION_STAY_IN_CATALOG: z.string().optional(),
  PUBLIC_SERVICE_FIELD_NAME_LABEL: z.string().optional(),
  PUBLIC_SERVICE_FIELD_CATEGORY_LABEL: z.string().optional(),
  PUBLIC_SERVICE_FIELD_DURATION_LABEL: z.string().optional(),
  PUBLIC_SERVICE_FIELD_PRICE_LABEL: z.string().optional(),
  PUBLIC_SERVICE_FIELD_DESCRIPTION_LABEL: z.string().optional(),
  PUBLIC_SERVICE_FORM_ADD_DESCRIPTION: z.string().optional(),
  PUBLIC_SERVICE_FORM_EDIT_DESCRIPTION: z.string().optional(),
  PUBLIC_SERVICE_VALIDATION_REQUIRED: z.string().optional(),
  PUBLIC_SERVICE_VALIDATION_DURATION: z.string().optional(),
  PUBLIC_SERVICE_ERROR_ADD: z.string().optional(),
  PUBLIC_SERVICE_ERROR_UPDATE: z.string().optional(),
  PUBLIC_SERVICE_ERROR_REMOVE: z.string().optional(),
  PUBLIC_PACKAGE_LABEL_SINGULAR: z.string().optional(),
  PUBLIC_PACKAGE_LABEL_PLURAL: z.string().optional(),
  PUBLIC_PACKAGE_MENU_TITLE: z.string().optional(),
  PUBLIC_PACKAGE_MENU_DESCRIPTION: z.string().optional(),
  PUBLIC_PACKAGE_EMPTY_TITLE: z.string().optional(),
  PUBLIC_PACKAGE_EMPTY_DESCRIPTION: z.string().optional(),
  PUBLIC_PACKAGE_ACTION_ADD: z.string().optional(),
  PUBLIC_PACKAGE_ACTION_EDIT: z.string().optional(),
  PUBLIC_PACKAGE_ACTION_REMOVE: z.string().optional(),
  PUBLIC_PACKAGE_ACTION_SAVE: z.string().optional(),
  PUBLIC_PACKAGE_ACTION_UPDATE: z.string().optional(),
  PUBLIC_PACKAGE_ACTION_SELL: z.string().optional(),
  PUBLIC_PACKAGE_ACTION_OPEN_REPORTS: z.string().optional(),
  PUBLIC_PACKAGE_ACTION_OPEN_CATALOG: z.string().optional(),
  PUBLIC_PACKAGE_FIELD_NAME_LABEL: z.string().optional(),
  PUBLIC_PACKAGE_FIELD_TOTAL_USES_LABEL: z.string().optional(),
  PUBLIC_PACKAGE_FIELD_PRICE_LABEL: z.string().optional(),
  PUBLIC_PACKAGE_FIELD_INCLUDED_SERVICES_LABEL: z.string().optional(),
  PUBLIC_PACKAGE_FORM_ADD_DESCRIPTION: z.string().optional(),
  PUBLIC_PACKAGE_FORM_EDIT_DESCRIPTION: z.string().optional(),
  PUBLIC_PACKAGE_VALIDATION_REQUIRED: z.string().optional(),
  PUBLIC_PACKAGE_ERROR_ADD: z.string().optional(),
  PUBLIC_PACKAGE_ERROR_UPDATE: z.string().optional(),
  PUBLIC_PACKAGE_ERROR_REMOVE: z.string().optional(),
  PUBLIC_PACKAGE_SOLD_LABEL: z.string().optional(),
  PUBLIC_PACKAGE_ACTIVE_BALANCES_LABEL: z.string().optional(),
  PUBLIC_PACKAGE_PUBLISHED_LABEL: z.string().optional(),
  PUBLIC_PRODUCT_LABEL_SINGULAR: z.string().optional(),
  PUBLIC_PRODUCT_LABEL_PLURAL: z.string().optional(),
  PUBLIC_PRODUCT_MENU_TITLE: z.string().optional(),
  PUBLIC_PRODUCT_MENU_DESCRIPTION: z.string().optional(),
  PUBLIC_PRODUCT_EMPTY_TITLE: z.string().optional(),
  PUBLIC_PRODUCT_EMPTY_DESCRIPTION: z.string().optional(),
  PUBLIC_PRODUCT_ACTION_ADD: z.string().optional(),
  PUBLIC_PRODUCT_ACTION_EDIT: z.string().optional(),
  PUBLIC_PRODUCT_ACTION_REMOVE: z.string().optional(),
  PUBLIC_PRODUCT_ACTION_SAVE: z.string().optional(),
  PUBLIC_PRODUCT_ACTION_UPDATE: z.string().optional(),
  PUBLIC_PRODUCT_ACTION_SELL: z.string().optional(),
  PUBLIC_PRODUCT_ACTION_VIEW_RECORDS: z.string().optional(),
  PUBLIC_PRODUCT_ACTION_OPEN_REPORTS: z.string().optional(),
  PUBLIC_PRODUCT_FIELD_NAME_LABEL: z.string().optional(),
  PUBLIC_PRODUCT_FIELD_CATEGORY_LABEL: z.string().optional(),
  PUBLIC_PRODUCT_FIELD_SKU_LABEL: z.string().optional(),
  PUBLIC_PRODUCT_FIELD_PRICE_LABEL: z.string().optional(),
  PUBLIC_PRODUCT_FIELD_STOCK_LABEL: z.string().optional(),
  PUBLIC_PRODUCT_FIELD_DESCRIPTION_LABEL: z.string().optional(),
  PUBLIC_PRODUCT_FIELD_QUANTITY_LABEL: z.string().optional(),
  PUBLIC_PRODUCT_FIELD_CUSTOMER_NAME_LABEL: z.string().optional(),
  PUBLIC_PRODUCT_FIELD_CUSTOMER_PHONE_LABEL: z.string().optional(),
  PUBLIC_PRODUCT_FIELD_CUSTOMER_EMAIL_LABEL: z.string().optional(),
  PUBLIC_PRODUCT_FORM_ADD_DESCRIPTION: z.string().optional(),
  PUBLIC_PRODUCT_FORM_EDIT_DESCRIPTION: z.string().optional(),
  PUBLIC_PRODUCT_SALES_DESCRIPTION: z.string().optional(),
  PUBLIC_PRODUCT_VALIDATION_REQUIRED: z.string().optional(),
  PUBLIC_PRODUCT_VALIDATION_STOCK: z.string().optional(),
  PUBLIC_PRODUCT_ERROR_ADD: z.string().optional(),
  PUBLIC_PRODUCT_ERROR_UPDATE: z.string().optional(),
  PUBLIC_PRODUCT_ERROR_REMOVE: z.string().optional(),
  PUBLIC_PRODUCT_ERROR_SELL: z.string().optional(),
  PUBLIC_PRODUCT_METRIC_ACTIVE_LABEL: z.string().optional(),
  PUBLIC_PRODUCT_METRIC_STOCK_LABEL: z.string().optional(),
  PUBLIC_PRODUCT_METRIC_SOLD_LABEL: z.string().optional(),
  PUBLIC_PRODUCT_METRIC_LOW_STOCK_LABEL: z.string().optional(),
  PUBLIC_PROFILE_TITLE_SUFFIX: z.string().optional(),
  PUBLIC_PROFILE_DESCRIPTION: z.string().optional(),
  PUBLIC_PROFILE_FIELD_BUSINESS_NAME_LABEL: z.string().optional(),
  PUBLIC_PROFILE_FIELD_BUSINESS_NAME_PLACEHOLDER: z.string().optional(),
  PUBLIC_PROFILE_FIELD_WEBSITE_LABEL: z.string().optional(),
  PUBLIC_PROFILE_FIELD_WEBSITE_PLACEHOLDER: z.string().optional(),
  PUBLIC_PROFILE_FIELD_PHONE_LABEL: z.string().optional(),
  PUBLIC_PROFILE_FIELD_PHONE_PLACEHOLDER: z.string().optional(),
  PUBLIC_PROFILE_FIELD_ADDRESS_LABEL: z.string().optional(),
  PUBLIC_PROFILE_FIELD_ADDRESS_PLACEHOLDER: z.string().optional(),
  PUBLIC_PROFILE_FIELD_IMAGE_LABEL: z.string().optional(),
  PUBLIC_PROFILE_FIELD_IMAGE_PLACEHOLDER: z.string().optional(),
  PUBLIC_PROFILE_ACTION_UPLOAD_IMAGE: z.string().optional(),
  PUBLIC_PROFILE_ACTION_REMOVE_IMAGE: z.string().optional(),
  PUBLIC_PROFILE_ACTION_SAVE: z.string().optional(),
  PUBLIC_PROFILE_VALIDATION_REQUIRED: z.string().optional(),
  PUBLIC_PROFILE_ERROR_UPDATE: z.string().optional(),
  PUBLIC_TEAM_MEMBER_LABEL_SINGULAR: z.string().optional(),
  PUBLIC_TEAM_MEMBER_LABEL_PLURAL: z.string().optional(),
  PUBLIC_TEAM_MEMBER_ROLE_OPTIONS: z.array(z.string().trim().min(1)).default([]),
  PUBLIC_TEAM_MEMBER_FIELD_OPENING_TIME_LABEL: z.string().optional(),
  PUBLIC_TEAM_MEMBER_FIELD_CLOSING_TIME_LABEL: z.string().optional(),
  PUBLIC_TEAM_MEMBER_FIELD_OFF_DAYS_LABEL: z.string().optional(),
  PUBLIC_TEAM_MEMBER_FIELD_OFF_DAYS_EMPTY: z.string().optional(),
  PUBLIC_BOOKING_LOCATION_LABEL: z.string().default(defaultBookingLocationLabel),
  PUBLIC_BOOKING_LOCATION_OPTION_PHYSICAL: z.string().default(defaultBookingLocationLabels.physical),
  PUBLIC_BOOKING_LOCATION_OPTION_MOBILE: z.string().default(defaultBookingLocationLabels.mobile),
  PUBLIC_BOOKING_LOCATION_OPTION_VIRTUAL: z.string().default(defaultBookingLocationLabels.virtual),
  PUBLIC_BOOKING_ADDRESS_LABEL: z.string().default(defaultBookingAddressLabel),
  PUBLIC_BOOKING_ADDRESS_PLACEHOLDER: z.string().default(defaultBookingAddressPlaceholder),
  PUBLIC_BOOKING_ADDRESS_HELP: z.string().default(defaultBookingAddressHelp),
  PUBLIC_BOOKING_ADDRESS_REQUIRED: z.string().default(defaultBookingAddressRequiredMessage),
  PUBLIC_BOOKING_PHONE_LABEL: z.string().default('Phone number'),
  PUBLIC_BOOKING_PHONE_HELP: z.string().default(
    'You and the business will receive SMS updates on this number.'
  ),
  PUBLIC_BOOKING_PHONE_COUNTRY_CODE_LABEL: z.string().default('Country code'),
  PUBLIC_BOOKING_PHONE_COUNTRY_CODE: z.string().default(''),
  PUBLIC_BOOKING_PHONE_NUMBER_PLACEHOLDER: z.string().default('Enter phone number'),
  PUBLIC_HOME_SEARCH_RESULTS_LIMIT: z.coerce.number().int().min(1).max(20).default(3),
  PUBLIC_LOCATION_SEARCH_COUNTRY_CODE: z.string().trim().min(2).max(3).optional(),
  PUBLIC_LOCATION_SEARCH_COUNTRY_LABEL: z.string().trim().min(1).optional(),
  LOCATION_SEARCH_PROVIDER_BASE_URL: z.string().url().optional(),
  TWILIO_ACCOUNT_SID: z.string().optional(),
  TWILIO_AUTH_TOKEN: z.string().optional(),
  TWILIO_PHONE_NUMBER: z.string().optional(),
  SALON_ADMIN_PHONE: z.string().optional()
});

const appEnv = process.env.APP_ENV ?? 'dev';

const resolvedEnv = {
  ...process.env,
  TRUST_PROXY: parseBooleanEnv(process.env.TRUST_PROXY, appEnv === 'prod'),
  PUBLIC_BASE_URL: normalizeBaseUrl(process.env.PUBLIC_BASE_URL),
  CORS_ALLOWED_ORIGINS: parseCorsOrigins(process.env.CORS_ALLOWED_ORIGINS),
  SUPABASE_URL: normalizeBaseUrl(process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL),
  SUPABASE_PUBLISHABLE_KEY:
    process.env.SUPABASE_PUBLISHABLE_KEY ??
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ??
    process.env.SUPABASE_ANON_KEY ??
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY?.trim(),
  ENABLE_PUBLIC_CUSTOMER_LOOKUPS: parseBooleanEnv(
    process.env.ENABLE_PUBLIC_CUSTOMER_LOOKUPS,
    appEnv !== 'prod'
  ),
  PUBLIC_SERVICE_LABEL_SINGULAR: process.env.PUBLIC_SERVICE_LABEL_SINGULAR?.trim(),
  PUBLIC_SERVICE_LABEL_PLURAL: process.env.PUBLIC_SERVICE_LABEL_PLURAL?.trim(),
  PUBLIC_SERVICE_MENU_TITLE: process.env.PUBLIC_SERVICE_MENU_TITLE?.trim(),
  PUBLIC_SERVICE_MENU_DESCRIPTION: process.env.PUBLIC_SERVICE_MENU_DESCRIPTION?.trim(),
  PUBLIC_SERVICE_COVERAGE_LABEL: process.env.PUBLIC_SERVICE_COVERAGE_LABEL?.trim(),
  PUBLIC_SERVICE_EMPTY_TITLE: process.env.PUBLIC_SERVICE_EMPTY_TITLE?.trim(),
  PUBLIC_SERVICE_EMPTY_DESCRIPTION: process.env.PUBLIC_SERVICE_EMPTY_DESCRIPTION?.trim(),
  PUBLIC_SERVICE_ACTION_ADD: process.env.PUBLIC_SERVICE_ACTION_ADD?.trim(),
  PUBLIC_SERVICE_ACTION_EDIT: process.env.PUBLIC_SERVICE_ACTION_EDIT?.trim(),
  PUBLIC_SERVICE_ACTION_REMOVE: process.env.PUBLIC_SERVICE_ACTION_REMOVE?.trim(),
  PUBLIC_SERVICE_ACTION_SAVE: process.env.PUBLIC_SERVICE_ACTION_SAVE?.trim(),
  PUBLIC_SERVICE_ACTION_UPDATE: process.env.PUBLIC_SERVICE_ACTION_UPDATE?.trim(),
  PUBLIC_SERVICE_ACTION_OPEN_BOOKING: process.env.PUBLIC_SERVICE_ACTION_OPEN_BOOKING?.trim(),
  PUBLIC_SERVICE_ACTION_STAY_IN_CATALOG: process.env.PUBLIC_SERVICE_ACTION_STAY_IN_CATALOG?.trim(),
  PUBLIC_SERVICE_FIELD_NAME_LABEL: process.env.PUBLIC_SERVICE_FIELD_NAME_LABEL?.trim(),
  PUBLIC_SERVICE_FIELD_CATEGORY_LABEL: process.env.PUBLIC_SERVICE_FIELD_CATEGORY_LABEL?.trim(),
  PUBLIC_SERVICE_FIELD_DURATION_LABEL: process.env.PUBLIC_SERVICE_FIELD_DURATION_LABEL?.trim(),
  PUBLIC_SERVICE_FIELD_PRICE_LABEL: process.env.PUBLIC_SERVICE_FIELD_PRICE_LABEL?.trim(),
  PUBLIC_SERVICE_FIELD_DESCRIPTION_LABEL: process.env.PUBLIC_SERVICE_FIELD_DESCRIPTION_LABEL?.trim(),
  PUBLIC_SERVICE_FORM_ADD_DESCRIPTION: process.env.PUBLIC_SERVICE_FORM_ADD_DESCRIPTION?.trim(),
  PUBLIC_SERVICE_FORM_EDIT_DESCRIPTION: process.env.PUBLIC_SERVICE_FORM_EDIT_DESCRIPTION?.trim(),
  PUBLIC_SERVICE_VALIDATION_REQUIRED: process.env.PUBLIC_SERVICE_VALIDATION_REQUIRED?.trim(),
  PUBLIC_SERVICE_VALIDATION_DURATION: process.env.PUBLIC_SERVICE_VALIDATION_DURATION?.trim(),
  PUBLIC_SERVICE_ERROR_ADD: process.env.PUBLIC_SERVICE_ERROR_ADD?.trim(),
  PUBLIC_SERVICE_ERROR_UPDATE: process.env.PUBLIC_SERVICE_ERROR_UPDATE?.trim(),
  PUBLIC_SERVICE_ERROR_REMOVE: process.env.PUBLIC_SERVICE_ERROR_REMOVE?.trim(),
  PUBLIC_PACKAGE_LABEL_SINGULAR: process.env.PUBLIC_PACKAGE_LABEL_SINGULAR?.trim(),
  PUBLIC_PACKAGE_LABEL_PLURAL: process.env.PUBLIC_PACKAGE_LABEL_PLURAL?.trim(),
  PUBLIC_PACKAGE_MENU_TITLE: process.env.PUBLIC_PACKAGE_MENU_TITLE?.trim(),
  PUBLIC_PACKAGE_MENU_DESCRIPTION: process.env.PUBLIC_PACKAGE_MENU_DESCRIPTION?.trim(),
  PUBLIC_PACKAGE_EMPTY_TITLE: process.env.PUBLIC_PACKAGE_EMPTY_TITLE?.trim(),
  PUBLIC_PACKAGE_EMPTY_DESCRIPTION: process.env.PUBLIC_PACKAGE_EMPTY_DESCRIPTION?.trim(),
  PUBLIC_PACKAGE_ACTION_ADD: process.env.PUBLIC_PACKAGE_ACTION_ADD?.trim(),
  PUBLIC_PACKAGE_ACTION_EDIT: process.env.PUBLIC_PACKAGE_ACTION_EDIT?.trim(),
  PUBLIC_PACKAGE_ACTION_REMOVE: process.env.PUBLIC_PACKAGE_ACTION_REMOVE?.trim(),
  PUBLIC_PACKAGE_ACTION_SAVE: process.env.PUBLIC_PACKAGE_ACTION_SAVE?.trim(),
  PUBLIC_PACKAGE_ACTION_UPDATE: process.env.PUBLIC_PACKAGE_ACTION_UPDATE?.trim(),
  PUBLIC_PACKAGE_ACTION_SELL: process.env.PUBLIC_PACKAGE_ACTION_SELL?.trim(),
  PUBLIC_PACKAGE_ACTION_OPEN_REPORTS: process.env.PUBLIC_PACKAGE_ACTION_OPEN_REPORTS?.trim(),
  PUBLIC_PACKAGE_ACTION_OPEN_CATALOG: process.env.PUBLIC_PACKAGE_ACTION_OPEN_CATALOG?.trim(),
  PUBLIC_PACKAGE_FIELD_NAME_LABEL: process.env.PUBLIC_PACKAGE_FIELD_NAME_LABEL?.trim(),
  PUBLIC_PACKAGE_FIELD_TOTAL_USES_LABEL: process.env.PUBLIC_PACKAGE_FIELD_TOTAL_USES_LABEL?.trim(),
  PUBLIC_PACKAGE_FIELD_PRICE_LABEL: process.env.PUBLIC_PACKAGE_FIELD_PRICE_LABEL?.trim(),
  PUBLIC_PACKAGE_FIELD_INCLUDED_SERVICES_LABEL: process.env.PUBLIC_PACKAGE_FIELD_INCLUDED_SERVICES_LABEL?.trim(),
  PUBLIC_PACKAGE_FORM_ADD_DESCRIPTION: process.env.PUBLIC_PACKAGE_FORM_ADD_DESCRIPTION?.trim(),
  PUBLIC_PACKAGE_FORM_EDIT_DESCRIPTION: process.env.PUBLIC_PACKAGE_FORM_EDIT_DESCRIPTION?.trim(),
  PUBLIC_PACKAGE_VALIDATION_REQUIRED: process.env.PUBLIC_PACKAGE_VALIDATION_REQUIRED?.trim(),
  PUBLIC_PACKAGE_ERROR_ADD: process.env.PUBLIC_PACKAGE_ERROR_ADD?.trim(),
  PUBLIC_PACKAGE_ERROR_UPDATE: process.env.PUBLIC_PACKAGE_ERROR_UPDATE?.trim(),
  PUBLIC_PACKAGE_ERROR_REMOVE: process.env.PUBLIC_PACKAGE_ERROR_REMOVE?.trim(),
  PUBLIC_PACKAGE_SOLD_LABEL: process.env.PUBLIC_PACKAGE_SOLD_LABEL?.trim(),
  PUBLIC_PACKAGE_ACTIVE_BALANCES_LABEL: process.env.PUBLIC_PACKAGE_ACTIVE_BALANCES_LABEL?.trim(),
  PUBLIC_PACKAGE_PUBLISHED_LABEL: process.env.PUBLIC_PACKAGE_PUBLISHED_LABEL?.trim(),
  PUBLIC_PRODUCT_LABEL_SINGULAR: process.env.PUBLIC_PRODUCT_LABEL_SINGULAR?.trim(),
  PUBLIC_PRODUCT_LABEL_PLURAL: process.env.PUBLIC_PRODUCT_LABEL_PLURAL?.trim(),
  PUBLIC_PRODUCT_MENU_TITLE: process.env.PUBLIC_PRODUCT_MENU_TITLE?.trim(),
  PUBLIC_PRODUCT_MENU_DESCRIPTION: process.env.PUBLIC_PRODUCT_MENU_DESCRIPTION?.trim(),
  PUBLIC_PRODUCT_EMPTY_TITLE: process.env.PUBLIC_PRODUCT_EMPTY_TITLE?.trim(),
  PUBLIC_PRODUCT_EMPTY_DESCRIPTION: process.env.PUBLIC_PRODUCT_EMPTY_DESCRIPTION?.trim(),
  PUBLIC_PRODUCT_ACTION_ADD: process.env.PUBLIC_PRODUCT_ACTION_ADD?.trim(),
  PUBLIC_PRODUCT_ACTION_EDIT: process.env.PUBLIC_PRODUCT_ACTION_EDIT?.trim(),
  PUBLIC_PRODUCT_ACTION_REMOVE: process.env.PUBLIC_PRODUCT_ACTION_REMOVE?.trim(),
  PUBLIC_PRODUCT_ACTION_SAVE: process.env.PUBLIC_PRODUCT_ACTION_SAVE?.trim(),
  PUBLIC_PRODUCT_ACTION_UPDATE: process.env.PUBLIC_PRODUCT_ACTION_UPDATE?.trim(),
  PUBLIC_PRODUCT_ACTION_SELL: process.env.PUBLIC_PRODUCT_ACTION_SELL?.trim(),
  PUBLIC_PRODUCT_ACTION_VIEW_RECORDS: process.env.PUBLIC_PRODUCT_ACTION_VIEW_RECORDS?.trim(),
  PUBLIC_PRODUCT_ACTION_OPEN_REPORTS: process.env.PUBLIC_PRODUCT_ACTION_OPEN_REPORTS?.trim(),
  PUBLIC_PRODUCT_FIELD_NAME_LABEL: process.env.PUBLIC_PRODUCT_FIELD_NAME_LABEL?.trim(),
  PUBLIC_PRODUCT_FIELD_CATEGORY_LABEL: process.env.PUBLIC_PRODUCT_FIELD_CATEGORY_LABEL?.trim(),
  PUBLIC_PRODUCT_FIELD_SKU_LABEL: process.env.PUBLIC_PRODUCT_FIELD_SKU_LABEL?.trim(),
  PUBLIC_PRODUCT_FIELD_PRICE_LABEL: process.env.PUBLIC_PRODUCT_FIELD_PRICE_LABEL?.trim(),
  PUBLIC_PRODUCT_FIELD_STOCK_LABEL: process.env.PUBLIC_PRODUCT_FIELD_STOCK_LABEL?.trim(),
  PUBLIC_PRODUCT_FIELD_DESCRIPTION_LABEL: process.env.PUBLIC_PRODUCT_FIELD_DESCRIPTION_LABEL?.trim(),
  PUBLIC_PRODUCT_FIELD_QUANTITY_LABEL: process.env.PUBLIC_PRODUCT_FIELD_QUANTITY_LABEL?.trim(),
  PUBLIC_PRODUCT_FIELD_CUSTOMER_NAME_LABEL: process.env.PUBLIC_PRODUCT_FIELD_CUSTOMER_NAME_LABEL?.trim(),
  PUBLIC_PRODUCT_FIELD_CUSTOMER_PHONE_LABEL: process.env.PUBLIC_PRODUCT_FIELD_CUSTOMER_PHONE_LABEL?.trim(),
  PUBLIC_PRODUCT_FIELD_CUSTOMER_EMAIL_LABEL: process.env.PUBLIC_PRODUCT_FIELD_CUSTOMER_EMAIL_LABEL?.trim(),
  PUBLIC_PRODUCT_FORM_ADD_DESCRIPTION: process.env.PUBLIC_PRODUCT_FORM_ADD_DESCRIPTION?.trim(),
  PUBLIC_PRODUCT_FORM_EDIT_DESCRIPTION: process.env.PUBLIC_PRODUCT_FORM_EDIT_DESCRIPTION?.trim(),
  PUBLIC_PRODUCT_SALES_DESCRIPTION: process.env.PUBLIC_PRODUCT_SALES_DESCRIPTION?.trim(),
  PUBLIC_PRODUCT_VALIDATION_REQUIRED: process.env.PUBLIC_PRODUCT_VALIDATION_REQUIRED?.trim(),
  PUBLIC_PRODUCT_VALIDATION_STOCK: process.env.PUBLIC_PRODUCT_VALIDATION_STOCK?.trim(),
  PUBLIC_PRODUCT_ERROR_ADD: process.env.PUBLIC_PRODUCT_ERROR_ADD?.trim(),
  PUBLIC_PRODUCT_ERROR_UPDATE: process.env.PUBLIC_PRODUCT_ERROR_UPDATE?.trim(),
  PUBLIC_PRODUCT_ERROR_REMOVE: process.env.PUBLIC_PRODUCT_ERROR_REMOVE?.trim(),
  PUBLIC_PRODUCT_ERROR_SELL: process.env.PUBLIC_PRODUCT_ERROR_SELL?.trim(),
  PUBLIC_PRODUCT_METRIC_ACTIVE_LABEL: process.env.PUBLIC_PRODUCT_METRIC_ACTIVE_LABEL?.trim(),
  PUBLIC_PRODUCT_METRIC_STOCK_LABEL: process.env.PUBLIC_PRODUCT_METRIC_STOCK_LABEL?.trim(),
  PUBLIC_PRODUCT_METRIC_SOLD_LABEL: process.env.PUBLIC_PRODUCT_METRIC_SOLD_LABEL?.trim(),
  PUBLIC_PRODUCT_METRIC_LOW_STOCK_LABEL: process.env.PUBLIC_PRODUCT_METRIC_LOW_STOCK_LABEL?.trim(),
  PUBLIC_PROFILE_TITLE_SUFFIX: process.env.PUBLIC_PROFILE_TITLE_SUFFIX?.trim(),
  PUBLIC_PROFILE_DESCRIPTION: process.env.PUBLIC_PROFILE_DESCRIPTION?.trim(),
  PUBLIC_PROFILE_FIELD_BUSINESS_NAME_LABEL: process.env.PUBLIC_PROFILE_FIELD_BUSINESS_NAME_LABEL?.trim(),
  PUBLIC_PROFILE_FIELD_BUSINESS_NAME_PLACEHOLDER: process.env.PUBLIC_PROFILE_FIELD_BUSINESS_NAME_PLACEHOLDER?.trim(),
  PUBLIC_PROFILE_FIELD_WEBSITE_LABEL: process.env.PUBLIC_PROFILE_FIELD_WEBSITE_LABEL?.trim(),
  PUBLIC_PROFILE_FIELD_WEBSITE_PLACEHOLDER: process.env.PUBLIC_PROFILE_FIELD_WEBSITE_PLACEHOLDER?.trim(),
  PUBLIC_PROFILE_FIELD_PHONE_LABEL: process.env.PUBLIC_PROFILE_FIELD_PHONE_LABEL?.trim(),
  PUBLIC_PROFILE_FIELD_PHONE_PLACEHOLDER:
    process.env.PUBLIC_PROFILE_FIELD_PHONE_PLACEHOLDER?.trim(),
  PUBLIC_PROFILE_FIELD_ADDRESS_LABEL: process.env.PUBLIC_PROFILE_FIELD_ADDRESS_LABEL?.trim(),
  PUBLIC_PROFILE_FIELD_ADDRESS_PLACEHOLDER: process.env.PUBLIC_PROFILE_FIELD_ADDRESS_PLACEHOLDER?.trim(),
  PUBLIC_PROFILE_FIELD_IMAGE_LABEL: process.env.PUBLIC_PROFILE_FIELD_IMAGE_LABEL?.trim(),
  PUBLIC_PROFILE_FIELD_IMAGE_PLACEHOLDER: process.env.PUBLIC_PROFILE_FIELD_IMAGE_PLACEHOLDER?.trim(),
  PUBLIC_PROFILE_ACTION_UPLOAD_IMAGE: process.env.PUBLIC_PROFILE_ACTION_UPLOAD_IMAGE?.trim(),
  PUBLIC_PROFILE_ACTION_REMOVE_IMAGE: process.env.PUBLIC_PROFILE_ACTION_REMOVE_IMAGE?.trim(),
  PUBLIC_PROFILE_ACTION_SAVE: process.env.PUBLIC_PROFILE_ACTION_SAVE?.trim(),
  PUBLIC_PROFILE_VALIDATION_REQUIRED: process.env.PUBLIC_PROFILE_VALIDATION_REQUIRED?.trim(),
  PUBLIC_PROFILE_ERROR_UPDATE: process.env.PUBLIC_PROFILE_ERROR_UPDATE?.trim(),
  PUBLIC_TEAM_MEMBER_LABEL_SINGULAR: process.env.PUBLIC_TEAM_MEMBER_LABEL_SINGULAR?.trim(),
  PUBLIC_TEAM_MEMBER_LABEL_PLURAL: process.env.PUBLIC_TEAM_MEMBER_LABEL_PLURAL?.trim(),
  PUBLIC_TEAM_MEMBER_ROLE_OPTIONS: parseStringList(process.env.PUBLIC_TEAM_MEMBER_ROLE_OPTIONS),
  PUBLIC_TEAM_MEMBER_FIELD_OPENING_TIME_LABEL: process.env.PUBLIC_TEAM_MEMBER_FIELD_OPENING_TIME_LABEL?.trim(),
  PUBLIC_TEAM_MEMBER_FIELD_CLOSING_TIME_LABEL: process.env.PUBLIC_TEAM_MEMBER_FIELD_CLOSING_TIME_LABEL?.trim(),
  PUBLIC_TEAM_MEMBER_FIELD_OFF_DAYS_LABEL: process.env.PUBLIC_TEAM_MEMBER_FIELD_OFF_DAYS_LABEL?.trim(),
  PUBLIC_TEAM_MEMBER_FIELD_OFF_DAYS_EMPTY: process.env.PUBLIC_TEAM_MEMBER_FIELD_OFF_DAYS_EMPTY?.trim(),
  PUBLIC_BOOKING_LOCATION_LABEL: process.env.PUBLIC_BOOKING_LOCATION_LABEL?.trim(),
  PUBLIC_BOOKING_LOCATION_OPTION_PHYSICAL: process.env.PUBLIC_BOOKING_LOCATION_OPTION_PHYSICAL?.trim(),
  PUBLIC_BOOKING_LOCATION_OPTION_MOBILE: process.env.PUBLIC_BOOKING_LOCATION_OPTION_MOBILE?.trim(),
  PUBLIC_BOOKING_LOCATION_OPTION_VIRTUAL: process.env.PUBLIC_BOOKING_LOCATION_OPTION_VIRTUAL?.trim(),
  PUBLIC_BOOKING_ADDRESS_LABEL: process.env.PUBLIC_BOOKING_ADDRESS_LABEL?.trim(),
  PUBLIC_BOOKING_ADDRESS_PLACEHOLDER: process.env.PUBLIC_BOOKING_ADDRESS_PLACEHOLDER?.trim(),
  PUBLIC_BOOKING_ADDRESS_HELP: process.env.PUBLIC_BOOKING_ADDRESS_HELP?.trim(),
  PUBLIC_BOOKING_ADDRESS_REQUIRED: process.env.PUBLIC_BOOKING_ADDRESS_REQUIRED?.trim(),
  PUBLIC_BOOKING_PHONE_LABEL: process.env.PUBLIC_BOOKING_PHONE_LABEL?.trim(),
  PUBLIC_BOOKING_PHONE_HELP: process.env.PUBLIC_BOOKING_PHONE_HELP?.trim(),
  PUBLIC_BOOKING_PHONE_COUNTRY_CODE_LABEL: process.env.PUBLIC_BOOKING_PHONE_COUNTRY_CODE_LABEL?.trim(),
  PUBLIC_BOOKING_PHONE_COUNTRY_CODE: process.env.PUBLIC_BOOKING_PHONE_COUNTRY_CODE?.trim(),
  PUBLIC_BOOKING_PHONE_NUMBER_PLACEHOLDER: process.env.PUBLIC_BOOKING_PHONE_NUMBER_PLACEHOLDER?.trim(),
  PUBLIC_HOME_SEARCH_RESULTS_LIMIT: process.env.PUBLIC_HOME_SEARCH_RESULTS_LIMIT,
  PUBLIC_LOCATION_SEARCH_COUNTRY_CODE: process.env.PUBLIC_LOCATION_SEARCH_COUNTRY_CODE?.trim().toLowerCase(),
  PUBLIC_LOCATION_SEARCH_COUNTRY_LABEL: process.env.PUBLIC_LOCATION_SEARCH_COUNTRY_LABEL?.trim(),
  LOCATION_SEARCH_PROVIDER_BASE_URL: normalizeBaseUrl(process.env.LOCATION_SEARCH_PROVIDER_BASE_URL),
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID ?? process.env.TWILIO_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN ?? process.env.TWILIO_TOKEN,
  TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER ?? process.env.TWILIO_FROM
};

const parsedEnv = envSchema.parse(resolvedEnv);

if (
  parsedEnv.CLIENT_PLATFORM_STORAGE === 'supabase' &&
  (!parsedEnv.SUPABASE_URL ||
    (!parsedEnv.SUPABASE_SERVICE_ROLE_KEY && !parsedEnv.SUPABASE_PUBLISHABLE_KEY))
) {
  throw new Error(
    'Supabase storage requires SUPABASE_URL and either SUPABASE_SERVICE_ROLE_KEY or SUPABASE_PUBLISHABLE_KEY.'
  );
}

export const env = parsedEnv;
